### ISSUE TITLE
Test Data Download

### ISSUE THREAD

**Issue by cliffbueno** [MathiasEskildsen/ONT-AmpSeq#5]
Hello,
I wanted to try this pipeline on the test data provided. There appears to be an issue with the test data download. Do you think this is an issue on my end or is there an issue with the ftp? Here's what happens (and it keeps retrying and getting the same error).

(base) [clbd1748@login13 samples]$ wget -O ERR12363979.fastq.gz ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR123/079/ERR12363979/ERR12363979.fastq.gz
--2024-09-25 12:05:47--  ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR123/079/ERR12363979/ERR12363979.fastq.gz
           => ‘ERR12363979.fastq.gz’
Resolving ftp.sra.ebi.ac.uk (ftp.sra.ebi.ac.uk)... 193.62.193.165
Connecting to ftp.sra.ebi.ac.uk (ftp.sra.ebi.ac.uk)|193.62.193.165|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /vol1/fastq/ERR123/079/ERR12363979 ... done.
==> SIZE ERR12363979.fastq.gz ... 14551828
==> PASV ... done.    ==> RETR ERR12363979.fastq.gz ... done.
Length: 14551828 (14M) (unauthoritative)

ERR12363979.fastq.gz                0%[                                                             ]       0  --.-KB/s    in 2.9s    

2024-09-25 12:05:51 (0.00 B/s) - Data transfer aborted.
Retrying.

**Comment by PSSchacksen** [comment]
Hi cliffbueno

Have you retried the download using wget?
I cannot reproduce the error using the command you supplied, using your direct command I am able to download the fastq file.
I can see that you are on a login node possibly? I am unsure of your permissions for downloading using this command. A alternative way of obtaining the files would be to download them manually from GitHub and transfer them to your system.

Best 
Patrick

**Comment by cliffbueno** [comment]
Yes, what I tried above was wget.

Ok, thanks for the suggestion.
